### ISSUE TITLE
文件打

### ISSUE THREAD

**Issue by tianfuzhou** [tencentyun/tls-sig-api-node#4]
引入这个打完包文件好大啊  有cdn方式引入的方式的吗

**Comment by okhowang** [comment]
这个不是给浏览器用的，web项目打包会引入node模块的各种polifill导致文件巨大。

**Comment by tianfuzhou** [comment]
那我可以在后台用php生成签名  然后前台登录使用吗

**Comment by tianfuzhou** [comment]
我试了好像不行  前台登录需要公钥  后台不需要
